### ISSUE TITLE
Blocks are aligning on opposite ends

### ISSUE THREAD

**Issue by corysimmons** [CrocoDillon/JustifyGrid#9]
I'm interested in this technique, but I can't seem to get the blocks to be left aligned when there is a strange number of them.

I just added 2 image elements to your demo and this is the result:

![image](https://cloud.githubusercontent.com/assets/224636/13169428/5f12d7a4-d6b3-11e5-8e42-226b8de1b5c9.png)

Do you happen to know how to fix this?

**Comment by corysimmons** [comment]
Changing the pseudo selector to from `width: 100%` to `auto` kinda works but breaks the gutters.

![image](https://cloud.githubusercontent.com/assets/224636/13169686/53204dc6-d6b5-11e5-9ce5-7bd3b994f571.png)

I'd just give `last-of-type { margin-left: 30px; }` but what happens if there are only 4 blocks in the grid? Then the 4th one would be pushed off the left side.

I'd do `nth-of-type(3n) { margin-right: 30px; }` but what if I want my 2nd block to be 2/3 instead of 1/3? Then it breaks the nth stuff.

**Comment by CrocoDillon** [comment]
I’m out all day today so can’t really give an elaborated response. But this has to do with having 5 elements while there is room for 6. Check figure 5 of [this article](http://www.barrelny.com/blog/text-align-justify-and-rwd/), that explains the problem and a possible solution rather well!

To be honest, I would just use flexbox. Browser support is pretty good and you can use inline-blocks as fallback for when flexbox is not supported.

**Comment by corysimmons** [comment]
Adding empty elements isn't ideal and flexbox suffers from the same problem. https://www.google.com/search?q=flexbox+space+between+last+row

**Comment by CrocoDillon** [comment]
Found a solution you might like, http://codepen.io/anon/pen/zrVOYj?editors=0100

Basically adds a right margin to the last element when needed. In the Pen it's `nth-child(3n)` because of the `<h1>`, but otherwise it would be `nth-child(3n - 1)`.

```scss
.image:nth-child(3n):last-child {
  @include grid-append(3, 9);
}
```

The logic is similar to the empty elements, without the empty elements. You need `n- 2` selectors where `n` is the number of columns (in this case 3 so that was easy).

Example with 4 columns, http://codepen.io/anon/pen/mVZbeb?editors=0100

```scss
&:nth-child(4n - 1):last-child {
  @include grid-append(3);
}
&:nth-child(4n - 2):last-child {
  @include grid-append(6);
}
```

**Comment by corysimmons** [comment]
Yeah, the unfortunate thing is we would have to know how many elements go in a row for nth to work. What if I want an element that is 1/3 and an element that is 2/3 in the first row, and just three 1/3 elements in the second row? nth stuff gets pretty hairy there.

I'm calling this "THE Problem" nowadays.

Justify (whether inline-block or flexbox) seems to be the only way to get elements to space out correctly without having to use margins (that would _have_ to be wrapped in a superfluous element).

The unfortunate part is that last row... It gets justified and elements get spaced out.

![image](https://cloud.githubusercontent.com/assets/224636/13197025/d539c928-d7ae-11e5-800d-a50953630026.png)

...or if you make the `:after { width: auto; }` it pushes all the last row elements to the left:

![image](https://cloud.githubusercontent.com/assets/224636/13197029/f57b919e-d7ae-11e5-9600-0d648f517df4.png)

...and when you try to add a margin to the last row of elements, you fall back into the "having to know how many elements" trap.

Here's a bare bone pen if you're interested in fighting with it, but I've been fighting with it for several days now.

http://codepen.io/corysimmons/pen/OMYjaP?editors=1100

My only hope is there is some obscure CSS property, or some crrrrrazy combination of nth selectors that will make this kind of stuff possible.

It'd be so nice to have the flexibility of Bootstrap-like grids without the extra markup.

**Comment by CrocoDillon** [comment]
That complicates things... Not sure if this is solvable in just CSS. If you know on the server how many columns you need to fill you can set a class that applies `margin-right` though. That would be the option I'd go for.

By the way with `:after { width: auto; }` you might as well remove the `:after` pseudo.

**Comment by corysimmons** [comment]
Yeah but the rule is we can't know how many or the size of the elements they're putting in the container. :)

> By the way with :after { width: auto; } you might as well remove the :after pseudo.

Yup. :+1:

**Comment by CrocoDillon** [comment]
Sorry about not responding anymore. I actually have no clue how to solve your issue.

**Comment by corysimmons** [comment]
Not a problem. I'm pretty confident it's unsolvable unless there is some weird CSS rule I haven't thought of using yet. I've fought with it for years. =)
